## 1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
Expected Output:<br>
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]<br>

In [4]:
import numpy 

lst = [1, 7, 0, 6, 2, 5, 6]

# converting list to array using array
arr = numpy.array(lst)

# converting list to array using asarray()
'''
The vital difference between the above two methods is that numpy.array() will make a duplicate 
of the original object and numpy.asarray() would mirror the changes in the original object. 
When a copy of the array is made by using numpy.asarray(), the changes made in one array 
would be reflected in the other array also but doesn’t show the changes in the list by which 
if the array is made.
'''
arr1 = numpy.asarray(lst)

print ("List:", lst)

print ("arr using array(): ", arr)

print ("arr1 using asarray(): ", arr1)

# made another array out of arr1 using asarray function
arr2 = numpy.asarray(arr1)

print("arr2 using asarray(): " , arr2)

arr2[3] = 23

#displaying arr, arr1 , arr2 , list after the change has been made
print("lst: " , lst)
print("arr using array():: " , arr)
print("arr1 using asarray(): " , arr1)
print("arr2 using asarray(): " , arr2)


List: [1, 7, 0, 6, 2, 5, 6]
arr using array():  [1 7 0 6 2 5 6]
arr1 using asarray():  [1 7 0 6 2 5 6]
arr2 using asarray():  [1 7 0 6 2 5 6]
lst:  [1, 7, 0, 6, 2, 5, 6]
arr using array()::  [1 7 0 6 2 5 6]
arr1 using asarray():  [ 1  7  0 23  2  5  6]
arr2 using asarray():  [ 1  7  0 23  2  5  6]


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]<br>

In [7]:
import numpy as np

matrix1 = np.arange(2, 11).reshape(3, 3)
print("Method 1:\n", matrix1)

matrix3 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print("Method 2:\n", matrix3)

matrix6 = np.array([i for i in range(2, 11)]).reshape(3, 3)
print("Method 3:\n", matrix6)

Method 1:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Method 2:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Method 3:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [8]:
import numpy as np
#array of zeros
null_vector = np.zeros(10)

null_vector[5] = 11

print(null_vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## 4. Write a Python program to reverse an array (first element becomes last).
Original array:<br>
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:<br>
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]<br>

In [12]:
import numpy as np

arr=np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

rev_arr=arr[::-1]
print(f"original array: {arr}")
print(f"reverse array: {rev_arr} ")

original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12] 


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Original array:<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>

In [15]:
import numpy as np

rows, cols = map(int, input("Enter the number of rows and columns separated by space: ").split())

array = np.ones((rows, cols))
print("original array:")
print(array)

array[1:-1, 1:-1] = 0

print("Updated array:")
print(array)


Enter the number of rows and columns separated by space: 9 9
original array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Updated array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:<br>
Original array:<br>
[[ 1. 1. 1.]<br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]<br>

In [20]:
import numpy as np

rows, cols = map(int, input("Enter the number of rows and columns separated by space: ").split())

array = np.ones((rows, cols))
print("original array:")
print(array)

updated_array=np.zeros((rows+2,cols+2))
updated_array[1:-1, 1:-1] = array

print("updated array:")
print(updated_array)

Enter the number of rows and columns separated by space: 2 3
original array:
[[1. 1. 1.]
 [1. 1. 1.]]
updated array:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]

In [24]:
import numpy as np

size =int( input("Enter the size of board: "))

array = np.zeros((size, size))
# print("original array:")
# print(array)

array[::2,1::2]=1
array[1::2,::2]=1
print("original array:")
print(array)


Enter the size of board: 8
original array:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
original array:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 8. Write a Python program to convert a list and tuple into arrays.
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>

In [25]:
import numpy as np

list_data = [1, 2, 3, 4, 5, 6, 7, 8]
array_from_list = np.array(list_data)

tuple_data = ((8, 4, 6), (1, 2, 3))
array_from_tuple = np.array(tuple_data)

print("List to array:")
print(array_from_list)

print("Tuple to array:")
print(array_from_tuple)


List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]


## 9. Write a Python program to append values to the end of an array.
Expected Output:<br>
Original array:<br>
[10, 20, 30]<br>

After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]<br>

In [26]:
import numpy as np

original_input = input("Enter the elements of the original array separated by spaces: ")
original_array = np.array([int(x) for x in original_input.split()])

append_input = input("Enter the values to append separated by spaces: ")
values_to_append = [int(x) for x in append_input.split()]

updated_array = np.append(original_array, values_to_append)

print("Original array:")
print(original_array)

print("Updated array:")
print(updated_array)


Enter the elements of the original array separated by spaces: 10 20 30
Enter the values to append separated by spaces: 40 50 60 70
Original array:
[10 20 30]
Updated array:
[10 20 30 40 50 60 70]


## 10. Write a Python program to find the real and imaginary parts of an array of complex numbers.
Expected Output:<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]<br>
Real part of the array:<br>
[ 1. 0.70710678]<br>
Imaginary part of the array:<br>
[ 0. 0.70710678]<br>

In [ ]:
import numpy as np

complex_array = np.array([1 + 0j, 0.70710678 + 0.70710678j])

real_part = complex_array.real

imaginary_part = complex_array.imag

print("Original array:")
print(complex_array)

print("Real part of the array:")
print(real_part)

print("Imaginary part of the array:")
print(imaginary_part)


## 11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.<br>
Expected Output:<br>
Size of the array: 3<br>
Length of one array element in bytes: 8<br>
Total bytes consumed by the elements of the array: 24<br>

In [32]:
import numpy as np

# original_input = input("Enter the elements of the array separated by spaces: ")
# array = np.array([int(x) for x in original_input.split()])
array = np.array([10, 20, 30, 40])

num_elements = array.size

element_size = array.itemsize

total_bytes = num_elements * element_size

print(f"Size of the array: {num_elements}")
print(f"Length of one array element in bytes: {element_size}")
print(f"Total bytes consumed by the elements of the array: {total_bytes}")


Size of the array: 4
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 16


## 13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
Expected Output:<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70, 90]<br>
Set difference between two arrays:<br>
[ 0 20 60 80]<br>

In [ ]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])
'''
numpy.setdiff1d() function find the set difference of two 
arrays and return the unique values in arr1 that are not in arr2.
'''
set_difference = np.setdiff1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Set difference between two arrays:")
print(set_difference)



## 14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70]<br>
Unique values that are in only one (not both) of the input arrays:<br>
[ 0 20 30 50 60 70 80]<br>


In [1]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
'''

'''
exclusive_or = np.setxor1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(exclusive_or)


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


## 15. Write a Python program compare two arrays using numpy.
Array a: [1 2]<br>
Array b: [4 5]<br>
a > b<br>
[False False]<br>
a >= b<br>
[False False]<br>
a < b<br>
[ True True]<br>
a <= b<br>
[ True True]<br>

In [2]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

greater_than = a > b
greater_than_or_equal = a >= b
less_than = a < b
less_than_or_equal = a <= b

print("a > b")
print(greater_than)

print("a >= b")
print(greater_than_or_equal)

print("a < b")
print(less_than)

print("a <= b")
print(less_than_or_equal)


a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


## 15. Write a Python program to save a NumPy array to a text file.


In [4]:
import numpy as np

# Create a NumPy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the array to a text file
np.savetxt('array.txt', array, fmt='%d')

print("Array saved to 'array.txt'")


Array saved to 'array.txt'


## 16. Write a Python program to create a contiguous flattened array.
Original array:<br>
[[10 20 30]<br>
[20 40 50]]<br>
New flattened array:<br>
[10 20 30 20 40 50]

In [5]:
import numpy as np

original_array = np.array([[10, 20, 30], [20, 40, 50]])

'''numpy.ndarray.flatten() function returns a copy of the array collapsed into one dimension.'''
flattened_array = original_array.flatten()

print("Original array:")
print(original_array)
print("New flattened array:")
print(flattened_array)


Original array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


## 17. Write a Python program to change the data type of an array.
Expected Output:<br>
[[ 2 4 6]<br>
[ 6 8 10]]<br>
Data type of the array x is: int32<br>
New Type: float64<br>
[[ 2. 4. 6.]<br>
[ 6. 8. 10.]]<br>

In [3]:
import numpy as np

array = np.array([[2, 4, 6], [6, 8, 10]])

print("Original array:")
print(array)
print("Data type of the array x is:", array.dtype)

new_array = array.astype(np.float64)

print(new_array)
print("New Type: float64")

Original array:
[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
New Type: float64


## 18. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [7]:
import numpy as np

import numpy as np

size =int( input("Enter the size of board: "))

array = np.zeros((size, size))
# print("original array:")
# print(array)

for i in range(size):
    array[i,i]=1
print("updated array:")
print(array)


# Create a 3-D array with ones on the diagonal and zeros elsewhere
# array = np.eye(3)
# print(array)

Enter the size of board: 8
updated array:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


## 19. Write a Python program to create an array which looks like below array.
Expected Output:<br>
[[ 0. 0. 0.]<br>
[ 1. 0. 0.]<br>
[ 1. 1. 0.]<br>
[ 1. 1. 1.]]<br>

In [21]:
import numpy as np

rows, cols = map(int, input("Enter the number of rows and columns separated by space: ").split())

array = np.zeros((rows, cols))
# print("original array:")
# print(array)

for i in range(1,rows):
    array[i, :i] = 1
    
print("original array:")
print(array)

Enter the number of rows and columns separated by space: 4 3
original array:
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## 20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:<br>
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]<br>
Expected Output:<br>
[[ 0 1 3 0 2 4]<br>
[ 5 7 9 6 8 10]]<br>

In [22]:
import numpy as np

array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print("Concatenated array:")
print(concatenated_array)

Concatenated array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


## 21. Write a Python program to make an array immutable (read-only).
Expected Output:<br>
Test the array is read-only or not:<br>
Try to change the value of the first element:<br>
Traceback (most recent call last):<br>
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in x[0] = 1<br>
ValueError: assignment destination is read-only<br>

In [24]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
'''
This set the writable flag to false and hence array becomes immutable i.e read-only.
'''
array.flags.writeable = False

print("Array:", array)

try:
    print("trying to replace first element of array: ")
    array[0] = 10
except ValueError as e:
    print("Error:", e)


Array: [1 2 3 4 5]
trying to replace first element of array: 
Error: assignment destination is read-only


## 22. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.
Expected Output:<br>
Original array elements:<br>
[[ 0 1 2 3]<br>
[ 4 5 6 7]<br>
[ 8 9 10 11]]<br>
New array elements:<br>
[[ 0 3 6 9]<br>
[12 15 18 21]<br>
[24 27 30 33]]<br>

In [29]:
import numpy as np

matrix1 = np.arange(12).reshape(3, 4)
print("array:\n", matrix1)

for i in range(3):
    for j in range(4):
        matrix1[i,j]=matrix1[i,j]*3
print("updated array:\n", matrix1)

array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
updated array:
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## 23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:<br>
Original array elements:<br>
[[0 1]<br>
[2 3]<br>
[4 5]]<br>
Array to list:<br>
[[0, 1], [2, 3], [4, 5]]<br>

In [30]:
import numpy as np

original_array = np.array([[0, 1], [2, 3], [4, 5]])

print("array elements:")
print(original_array)
'''
we use ndarray.tolist method of NumPy library in Python. It returns a copy of
the array data as a Python list (Nested list in case of a multi-dimensional array).
'''
array_to_list = original_array.tolist()

print("Array to list:")
print(array_to_list)


array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


## 24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:<br>
Original array elements:<br>
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349<br>
0.35399976 0.99469633 0.0694458 0.54711478]<br>
Print array values with precision 3:<br>
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]<br>

In [33]:
import numpy as np

# Create the original array with random float values
original_array = np.random.rand(10)

# Print the original array
print("Original array elements:")
print(original_array)

for i in len(original_array):
    original_array[i]
    

print("array values with precision 3:")
print([f"{x:.3f}" for x in original_array])

array_to_list = original_array.tolist()
print("list values with precision 3:")
print([f"{x:.3f}" for x in array_to_list])


Original array elements:
[0.68399722 0.15459487 0.92245599 0.25514085 0.55497113 0.17468262
 0.58715461 0.11674101 0.37944229 0.94500233]
array values with precision 3:
['0.684', '0.155', '0.922', '0.255', '0.555', '0.175', '0.587', '0.117', '0.379', '0.945']
list values with precision 3:
['0.684', '0.155', '0.922', '0.255', '0.555', '0.175', '0.587', '0.117', '0.379', '0.945']


## 25. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array.
Expected Output:<br>
Original array elements:<br>
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]<br>
Print array values with precision 3:<br>
[ 0. 1.6 1200. 0.235]<br>

In [34]:
import numpy as np

original_array = np.array([1.6e-10, 1.6, 1200, 0.235])

print("Original array elements:")
print(original_array)

np.set_printoptions(suppress=True, precision=3)

print("Print array values with precision 3:")
print(original_array)

Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


## 26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:<br>
[[ 10 20 30 100]<br>
[ 40 50 60 200]]

In [36]:
import numpy as np

original_array = np.array([[10, 20, 30], [40, 50, 60]])
new_column = np.array([[100], [200]])

'''
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.
axis : [int, optional] The axis along which the arrays will be joined. If axis is None,
arrays are flattened before use. Default is 0.
'''
result_array = np.concatenate((original_array, new_column), axis=1)
print("Array using concatenate:")
print(result_array)


'''
numpy.column_stack() function is used to stack 1-D arrays as columns into a 2-D array.
It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array.
2-D arrays are stacked as-is, just like with hstack function.
'''
result_array = np.column_stack((original_array, new_column))
print("Array with extra column:")
print(result_array)


'''
numpy.hstack() function is used to stack the sequence of 
input arrays horizontally (i.e. column wise) to make a single array.
'''
result_array = np.hstack((original_array, new_column))
print("Array with extra column:")
print(result_array)

Array using concatenate:
[[ 10  20  30 100]
 [ 40  50  60 200]]
Array with extra column:
[[ 10  20  30 100]
 [ 40  50  60 200]]
Array with extra column:
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [41]:
import numpy as geek 
  
arr1 = geek.array([[2, 4], [6, 8]]) 
arr2 = geek.array([[3, 5], [7, 9]]) 
  
gfg = geek.concatenate((arr1, arr2), axis = 1) 
print (gfg) 

[[2 4 3 5]
 [6 8 7 9]]


In [ ]:
import numpy as np

# Create the original array
original_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Specify indices of elements to delete (1-based index converted to 0-based)
indices_to_delete = [0, 3, 4]  # Removing first, fourth, and fifth elements

# Delete the specified elements
new_array = np.delete(original_array, indices_to_delete)

# Print the original and new arrays
print("Original array:")
print(original_array)
print("Delete first, fourth and fifth elements:")
print(new_array)


In [43]:
import numpy as np

print("Enter the elements of the array separated by spaces:")
user_input = input()
elements = list(map(float, user_input.split()))
array = np.array(elements)

print("Enter the index of the array want you to delete:")
user_input = input()
index = list(map(int, user_input.split()))

new_array=np.delete(array,index)

print(f"original array: {array}")
print(f"Updated array: {new_array}")

Enter the elements of the array separated by spaces:
0 10 20 30 40 50
Enter the index of the array want you to delete:
2 4
original array: [ 0. 10. 20. 30. 40. 50.]
Updated array: [ 0. 10. 30. 50.]
