## 1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
Expected Output:<br>
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]<br>

In [4]:
import numpy 

lst = [1, 7, 0, 6, 2, 5, 6]

# converting list to array using array
arr = numpy.array(lst)

# converting list to array using asarray()
'''
The vital difference between the above two methods is that numpy.array() will make a duplicate 
of the original object and numpy.asarray() would mirror the changes in the original object. 
When a copy of the array is made by using numpy.asarray(), the changes made in one array 
would be reflected in the other array also but doesn’t show the changes in the list by which 
if the array is made.
'''
arr1 = numpy.asarray(lst)

print ("List:", lst)

print ("arr using array(): ", arr)

print ("arr1 using asarray(): ", arr1)

# made another array out of arr1 using asarray function
arr2 = numpy.asarray(arr1)

print("arr2 using asarray(): " , arr2)

arr2[3] = 23

#displaying arr, arr1 , arr2 , list after the change has been made
print("lst: " , lst)
print("arr using array():: " , arr)
print("arr1 using asarray(): " , arr1)
print("arr2 using asarray(): " , arr2)


List: [1, 7, 0, 6, 2, 5, 6]
arr using array():  [1 7 0 6 2 5 6]
arr1 using asarray():  [1 7 0 6 2 5 6]
arr2 using asarray():  [1 7 0 6 2 5 6]
lst:  [1, 7, 0, 6, 2, 5, 6]
arr using array()::  [1 7 0 6 2 5 6]
arr1 using asarray():  [ 1  7  0 23  2  5  6]
arr2 using asarray():  [ 1  7  0 23  2  5  6]


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]<br>

In [7]:
import numpy as np

matrix1 = np.arange(2, 11).reshape(3, 3)
print("Method 1:\n", matrix1)

matrix3 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print("Method 2:\n", matrix3)

matrix6 = np.array([i for i in range(2, 11)]).reshape(3, 3)
print("Method 3:\n", matrix6)

Method 1:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Method 2:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Method 3:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [8]:
import numpy as np
#array of zeros
null_vector = np.zeros(10)

null_vector[5] = 11

print(null_vector)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


## 4. Write a Python program to reverse an array (first element becomes last).
Original array:<br>
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:<br>
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]<br>

In [12]:
import numpy as np

arr=np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

rev_arr=arr[::-1]
print(f"original array: {arr}")
print(f"reverse array: {rev_arr} ")

original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12] 


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Original array:<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br>

In [15]:
import numpy as np

rows, cols = map(int, input("Enter the number of rows and columns separated by space: ").split())

array = np.ones((rows, cols))
print("original array:")
print(array)

array[1:-1, 1:-1] = 0

print("Updated array:")
print(array)


Enter the number of rows and columns separated by space: 9 9
original array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Updated array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:<br>
Original array:<br>
[[ 1. 1. 1.]<br>
[ 1. 1. 1.]<br>
[ 1. 1. 1.]]<br>
1 on the border and 0 inside in the array<br>
[[ 0. 0. 0. 0. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 1. 1. 1. 0.]<br>
[ 0. 0. 0. 0. 0.]]<br>

In [20]:
import numpy as np

rows, cols = map(int, input("Enter the number of rows and columns separated by space: ").split())

array = np.ones((rows, cols))
print("original array:")
print(array)

updated_array=np.zeros((rows+2,cols+2))
updated_array[1:-1, 1:-1] = array

print("updated array:")
print(updated_array)

Enter the number of rows and columns separated by space: 2 3
original array:
[[1. 1. 1.]
 [1. 1. 1.]]
updated array:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:<br>
[[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]<br>
[0 1 0 1 0 1 0 1]<br>
[1 0 1 0 1 0 1 0]]

In [24]:
import numpy as np

size =int( input("Enter the size of board: "))

array = np.zeros((size, size))
# print("original array:")
# print(array)

array[::2,1::2]=1
array[1::2,::2]=1
print("original array:")
print(array)


Enter the size of board: 8
original array:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
original array:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 8. Write a Python program to convert a list and tuple into arrays.
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>

In [25]:
import numpy as np

list_data = [1, 2, 3, 4, 5, 6, 7, 8]
array_from_list = np.array(list_data)

tuple_data = ((8, 4, 6), (1, 2, 3))
array_from_tuple = np.array(tuple_data)

print("List to array:")
print(array_from_list)

print("Tuple to array:")
print(array_from_tuple)


List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]


## 9. Write a Python program to append values to the end of an array.
Expected Output:<br>
Original array:<br>
[10, 20, 30]<br>

After append values to the end of the array:<br>
[10 20 30 40 50 60 70 80 90]<br>

In [26]:
import numpy as np

original_input = input("Enter the elements of the original array separated by spaces: ")
original_array = np.array([int(x) for x in original_input.split()])

append_input = input("Enter the values to append separated by spaces: ")
values_to_append = [int(x) for x in append_input.split()]

updated_array = np.append(original_array, values_to_append)

print("Original array:")
print(original_array)

print("Updated array:")
print(updated_array)


Enter the elements of the original array separated by spaces: 10 20 30
Enter the values to append separated by spaces: 40 50 60 70
Original array:
[10 20 30]
Updated array:
[10 20 30 40 50 60 70]


## 10. Write a Python program to find the real and imaginary parts of an array of complex numbers.
Expected Output:<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]<br>
Real part of the array:<br>
[ 1. 0.70710678]<br>
Imaginary part of the array:<br>
[ 0. 0.70710678]<br>

In [ ]:
import numpy as np

complex_array = np.array([1 + 0j, 0.70710678 + 0.70710678j])

real_part = complex_array.real

imaginary_part = complex_array.imag

print("Original array:")
print(complex_array)

print("Real part of the array:")
print(real_part)

print("Imaginary part of the array:")
print(imaginary_part)


## 11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.<br>
Expected Output:<br>
Size of the array: 3<br>
Length of one array element in bytes: 8<br>
Total bytes consumed by the elements of the array: 24<br>

In [32]:
import numpy as np

# original_input = input("Enter the elements of the array separated by spaces: ")
# array = np.array([int(x) for x in original_input.split()])
array = np.array([10, 20, 30, 40])

num_elements = array.size

element_size = array.itemsize

total_bytes = num_elements * element_size

print(f"Size of the array: {num_elements}")
print(f"Length of one array element in bytes: {element_size}")
print(f"Total bytes consumed by the elements of the array: {total_bytes}")


Size of the array: 4
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 16


## 13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.
Expected Output:<br>
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70, 90]<br>
Set difference between two arrays:<br>
[ 0 20 60 80]<br>

In [ ]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])
'''
numpy.setdiff1d() function find the set difference of two 
arrays and return the unique values in arr1 that are not in arr2.
'''
set_difference = np.setdiff1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Set difference between two arrays:")
print(set_difference)



## 14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]<br>
Array2: [10, 30, 40, 50, 70]<br>
Unique values that are in only one (not both) of the input arrays:<br>
[ 0 20 30 50 60 70 80]<br>


In [ ]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
'''

'''
exclusive_or = np.setxor1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(exclusive_or)
